### ISSUE TITLE
Release/tag 1.2.0 doesn't seem to be associated with any branch

### ISSUE THREAD

**Issue by turbomam** [PennTURBO/med_mapping#36]
Release/tag `1.2.0` doesn't seem to be associated with any branch, let alone master

If I specifically checkout the `1.2.0` tagged commit, everything looks fine

```
(base) ibi-admin-017:medication-knowledgegraph-pipeline markampa$ git fetch --all --tags
Fetching origin
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Total 3 (delta 1), reused 3 (delta 1), pack-reused 0
Unpacking objects: 100% (3/3), done.
From https://github.com/PennTURBO/medication-knowledgegraph-pipeline
 * [new tag]         1.2.0      -> 1.2.0
 
(base) ibi-admin-017:medication-knowledgegraph-pipeline markampa$ git checkout tags/1.2.0
HEAD is now at 75484b0 dumped last version metadata to last_*.txt files

(base) ibi-admin-017:medication-knowledgegraph-pipeline markampa$ git describe --tags
1.2.0
```

But that tag hasn't been applied to the master branch, so running the scripts in the master branch results in writing the wrong version statements into the triplestore

Does it make sense that `1.2.0` is detached from `HEAD`? Does it make sense that `master` appears on three diffent lines on the branch list?

```(base) ibi-admin-017:medication-knowledgegraph-pipeline markampa$ git branch -a
* (HEAD detached at 1.2.0)
  action-versioning
  master
  remotes/origin/HEAD -> origin/master
  remotes/origin/action-versioning
  remotes/origin/dev
  remotes/origin/master
  remotes/origin/versioning
```

**Comment by hjwilli** [comment]
Hi @turbomam, I agree that something is off here and am taking a look.  What method did you use to create the tag?

**Comment by hjwilli** [comment]
Figured it out. The issue is how the github action is applying commits:
https://github.com/PennTURBO/medication-knowledgegraph-pipeline/blob/245a86f1834dc7172f110713d5dfc57f7ca44f12/.github/workflows/push-version-metadata.yml#L37-L44

When a github action is triggered by a publish action the value of ${{ github.ref }} is the tag associated with the publish (see [here]( https://docs.github.com/en/actions/reference/events-that-trigger-workflows#release)). When you make a release the commit is not being applied to the master branch, but to the tag reference with the `--force` and `--tag` flags. 


See the '**push changes**' section of log here (action triggered by a publish, commit applied to tag):
https://github.com/PennTURBO/medication-knowledgegraph-pipeline/runs/1787664284?check_suite_focus=true

vs here (triggered manually, commit applied to master as expected):
https://github.com/PennTURBO/medication-knowledgegraph-pipeline/runs/1787670083?check_suite_focus=true

**Comment by turbomam** [comment]
Thanks @hjwilli . Apologies for not responding sooner. I'll look though the links you provided. Can we touch base in our TURBO meeting at 1:30?

**Comment by turbomam** [comment]
Took `upgrade_version.yml` action from `hjwilli/medication-knowledgegraph-pipeline`
